schema_version: "1.0"
name: "Plan Quality 5‑Point Judge"
version: "1.0"
description: >
  Compares unrevised plan to final revised plan against the original user goal
  using a 1‑5 ordinal rubric stored in the result JSON.

ingestion:
  type: python
  config:
    script_path: core/ingestion/agento_analytical_ingester.py
    entry_function: ingest_agento_analytical_trace
    mode: "plan_delta"

pipeline:
  - name: "plan_quality_judge"
    scorer: llm_judge
    config:
      provider: openai
      model: gpt-4o
      temperature: 0.0
      system_prompt: |
        You are an external reviewer. Only consider the user's original goal,
        the first full plan, and the final revised plan. Use the rubric and
        think step‑by‑step before deciding.
        Output JSON: {"score": 1‑5, "reasoning": string}.
      user_prompt_template: |
        ## Original goal
        {{ input }}

        ## First full plan
        {{ expected_output }}

        ## Final revised plan
        {{ output }}

        RUBRIC
        5 – Significantly more likely to achieve the goal  
        4 – Somewhat more likely  
        3 – About as likely  
        2 – Somewhat less likely  
        1 – Significantly less likely