[tool.poetry]
name = "ai-eval-workbench"
version = "0.1.0"
description = "Streamlit based LLM evaluation workbench"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
streamlit = "*"
pydantic = "*"

[tool.poetry.dev-dependencies]
pytest = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
