schema_version: "1.0"
name: "Test OTEL Pack"
version: "1.0"
description: "Test pack for OTEL JSON ingestion"
author: "Lake Merritt Team"

ingestion:
  type: generic_otel
  config:
    input_field: "attributes.input"
    output_field: "attributes.output"
    expected_output_field: "attributes.expected_output"
    default_expected_output: "No expected output"

pipeline:
  - name: "Exact Match Check"
    scorer: exact_match
    config:
      case_sensitive: false
    on_fail: continue