schema_version: "1.0"
name: "CSV quick check"
ingestion:
  type: csv
  config: { mode: evaluate_existing }

pipeline:
  - name: fuzzy
    scorer: fuzzy_match
    config: { threshold: 0.85 }
  - name: judge
    scorer: llm_judge
    config:
      provider: openai
      model: gpt-4o
      threshold: 0.7
      user_prompt_template: |
        Input: {{ input }}
        Expected: {{ expected_output }}
        Actual: {{ output }}
        Respond in JSON with "score" and "reasoning".
