# JSON Evaluation with LLM Judge
# This example shows how to evaluate JSON data using an LLM as a judge

schema_version: "1.0"
name: "JSON LLM Judge Evaluation"
version: "1.0"
description: "Evaluation pack using LLM judge for quality assessment of JSON data"
author: "Lake Merritt Team"

ingestion:
  type: "json"
  config:
    mode: "evaluate_existing"

pipeline:
  - name: "Basic Exact Match"
    scorer: "exact_match"
    config:
      case_sensitive: false
    on_fail: "continue"
  
  - name: "LLM Quality Judge"
    scorer: "llm_judge"
    config:
      model: "gpt-4"
      temperature: 0.0
      criteria:
        - "The output accurately addresses the input question"
        - "The output is clear and well-structured"
        - "The output provides complete information"
      threshold: 0.7
    on_fail: "continue"

reporting:
  format: "markdown"
  template: "detailed"

metadata:
  tags: ["json", "llm", "quality", "example"]
  difficulty: "intermediate"
  estimated_cost: "medium"  # Due to LLM API calls