schema_version: "1.0"
name: "Legal Citations Evaluation (Streamlit Compatible)"
version: "1.0"
description: "Multi-stage evaluation for legal citations using only base scorers available on Streamlit Cloud"
author: "Lake Merritt Team"

ingestion:
  type: "csv"

pipeline:
  # Stage 1: Exact match with normalization
  - name: "exact_match_normalized"
    scorer: "exact_match"
    config:
      case_sensitive: false
      normalize_whitespace: true
    on_fail: "continue"
  
  # Stage 2: Fuzzy match for minor variations
  - name: "fuzzy_match_high_threshold"
    scorer: "fuzzy_match"
    config:
      threshold: 0.9  # Very high threshold for legal citations
    on_fail: "continue"
  
  # Stage 3: Fuzzy match with lower threshold
  - name: "fuzzy_match_medium_threshold"
    scorer: "fuzzy_match"
    config:
      threshold: 0.8  # Medium threshold to catch more variations
    on_fail: "continue"
  
  # Stage 4: LLM semantic judge with detailed analysis
  - name: "semantic_citation_judge"
    scorer: "llm_judge"
    config:
      provider: "openai"
      model: "gpt-4o"
      threshold: 0.7
      temperature: 0.1
      system_prompt: |
        You are an expert legal citation validator. Analyze citations for accuracy and format.
        Return JSON with: "score" (0-1), "passed" (boolean), "reasoning" (string), "errors" (list).
      user_prompt_template: |
        Compare these legal citations for substantive accuracy and formatting:
        
        **Scoring Guidelines:**
        - 1.0: Identical citation (substance and format)
        - 0.9: Same case, minor punctuation/spacing differences
        - 0.8: Same case, different abbreviation style (e.g., "U.S." vs "US")
        - 0.7: Same case, missing/extra periods or commas
        - 0.5: Same case, different citation format
        - 0.3: Partially correct (wrong page/year but right case)
        - 0.0: Different case or fundamentally wrong
        
        **Common Variations to Accept:**
        - "U.S." vs "US" vs "U. S."
        - Single vs double spaces
        - "Int'l" vs "International"
        - "Comm'r" vs "Commissioner"
        - En dash (–) vs hyphen (-)
        - Smart quotes vs regular quotes
        
        **Expected:** {expected_output}
        **Actual:** {output}
        **Input:** {input}
    on_fail: "continue"

reporting:
  format: "markdown"
  include_details: true

metadata:
  tags: ["legal", "citations", "streamlit-compatible"]
  notes: "Uses only base scorers that are guaranteed to be available on Streamlit Cloud"