# OpenTelemetry Tool Usage Evaluation
# This example shows how to evaluate OTEL traces for proper tool usage

schema_version: "1.0"
name: "OTEL Tool Usage Evaluation"
version: "1.0"
description: "Evaluates OpenTelemetry traces to ensure proper tool usage patterns"
author: "Lake Merritt Team"

ingestion:
  type: "generic_otel"
  config:
    span_kind_filter: ["TOOL", "LLM"]
    input_field: "attributes.input.messages.0.content"
    output_field: "attributes.output.content"
    default_expected_output: "Tool usage should be appropriate for the task"
    include_trace_context: true
    metadata_fields:
      tool_name: "attributes.tool.name"
      tool_status: "status.code"

pipeline:
  - name: "Tool Usage Pattern Check"
    scorer: "tool_usage"
    config:
      required_tools: ["search", "calculator"]
      forbidden_tools: ["delete", "admin"]
      check_sequence: true
      expected_sequence: ["search", "calculator", "summarize"]
      min_usage_count:
        search: 1
      max_usage_count:
        calculator: 3
      threshold: 0.8
    on_fail: "continue"
    span_kind: "TOOL"  # Only run on TOOL spans
  
  - name: "LLM Output Quality"
    scorer: "llm_judge"
    config:
      model: "gpt-3.5-turbo"
      temperature: 0.0
      criteria:
        - "The LLM output appropriately uses the tool results"
        - "The final answer is based on tool outputs"
      threshold: 0.7
    on_fail: "continue"
    span_kind: "LLM"  # Only run on LLM spans

reporting:
  format: "markdown"
  template: "trace_analysis"

metadata:
  tags: ["otel", "tools", "traces", "advanced", "example"]
  difficulty: "advanced"
  trace_format: "opentelemetry"