# otel-agento-criteria-eval-pack.yaml  – drop into examples/eval_packs/

schema_version: "1.0"
name: "OTel Agent — Criteria-Reasonableness Evaluation"
version: "0.1"
description: >
  Ingest an OpenTelemetry trace produced by the agent prototype and let an
  LLM judge whether the three “selected_criteria” for each goal are
  collectively reasonable measures of success.

author: "Lake Merritt Team (desktop prototype)"

###############################################################################
# 1  INGESTION  – uses the new PythonIngester you just added
###############################################################################
ingestion:
  type: "python"                               # must match registry key
  script_path: "module1_opentelemetry_gm_1156.py"  # file renamed to import-safe
  entry_function: "ingest_otel_to_evalitems"
  config:
    trace_file: "manual_traces.json"           # any extra keys your helper needs

###############################################################################
# 2  EVALUATION PIPELINE
###############################################################################
pipeline:
  - name:   "criteria_reasonableness"
    scorer: "llm_judge"
    config:
      provider: "openai"
      model:    "gpt-4o"
      temperature: 0.1
      threshold: 0.7            # ≥ 0.70 → passes

      system_prompt: |
        You are a rigorous evaluation expert. Your job is to decide whether a
        set of three success-criteria, taken together, provide a sensible,
        distinct, and measurable way to judge whether the *goal* has been
        achieved. Respond ONLY in valid JSON using the schema below.

        Required JSON schema:
        {
          "score":     float,   # 1.0 = fully reasonable, 0.0 = not reasonable
          "reasoning": string   # 2–4 sentences explaining the score
        }

      user_prompt_template: |
        ## Goal
        {input}

        ## Candidate Criteria (exactly three, selected by the agent)
        {output}

        ## Instructions
        1. Read the goal carefully.
        2. Read the three criteria and judge whether, *together*, they give a
           clear, measurable signal of success for that goal.
        3. Think about coverage (do they address all key aspects?), overlap
           (are they distinct?), and practicality (can the user actually
           measure them?).
        4. Produce the JSON object described in the system prompt.
