# Test Case 1: Invalid YAML Syntax
# This file has indentation errors and missing colons

schema_version: "1.0"
name: "Invalid Syntax Pack"
version "1.0.0"  # Missing colon
description: "Test pack with YAML syntax errors"

ingestion:
  type: "csv"
  parameters:
    file_path: "test.csv"
      header: true  # Incorrect indentation
    delimiter: ","

pipeline:
  - name: "Test Stage"
    scorer: "exact_match"
    on_fail: "continue"
   expected_key "actual_value"  # Missing colon and wrong indentation