# Test Case 2: Unknown Ingester
# This file has valid YAML syntax but references an unknown ingester

schema_version: "1.0"
name: "Unknown Ingester Pack"
version: "1.0.0"
description: "Test pack with unknown ingester type"

ingestion:
  type: "unknown_ingester_type"  # This ingester doesn't exist
  parameters:
    some_param: "value"

pipeline:
  - name: "Valid Stage"
    scorer: "exact_match"
    on_fail: "continue"
    expected_key: "expected"
    actual_key: "actual"

reporting:
  format: "markdown"
  include_metadata: true