# Test Case 4: Valid Pack
# This file has correct YAML syntax and all components exist

schema_version: "1.0"
name: "Valid Test Pack"
version: "1.0.0"
description: "A fully valid test pack for verification"

ingestion:
  type: "csv"  # Valid ingester
  parameters:
    file_path: "test_data.csv"
    header: true
    delimiter: ","

pipeline:
  - name: "Exact Match Stage"
    scorer: "exact_match"  # Valid scorer
    on_fail: "continue"
    expected_key: "expected_response"
    actual_key: "actual_response"
  
  - name: "Fuzzy Match Stage"
    scorer: "fuzzy_match"  # Valid scorer
    on_fail: "stop"
    expected_key: "expected_output"
    actual_key: "actual_output"
    parameters:
      threshold: 0.8
  
  - name: "LLM Judge Stage"
    scorer: "llm_judge"  # Valid scorer
    on_fail: "continue"
    expected_key: "expected"
    actual_key: "actual"
    parameters:
      model: "gpt-4"
      criteria: "Check if the response is accurate and helpful"

reporting:
  format: "markdown"  # Valid format
  include_metadata: true
  output_path: "reports/test_report.md"