# Test Case 5: Invalid on_fail value
# This file has valid YAML syntax but invalid on_fail value

schema_version: "1.0"
name: "Invalid on_fail Pack"
version: "1.0.0"
description: "Test pack with invalid on_fail value"

ingestion:
  type: "json"  # Valid ingester
  parameters:
    file_path: "test.json"

pipeline:
  - name: "Stage with Invalid on_fail"
    scorer: "exact_match"  # Valid scorer
    on_fail: "skip"  # Invalid - should be "continue" or "stop"
    expected_key: "expected"
    actual_key: "actual"

reporting:
  format: "pdf"  # Valid format
  include_metadata: true